#!/usr/bin/node
let fs = require('fs')
let { exec,spawn } = require('child_process')

if(process.env['req_body_method'] == 'WEBSOCKET'){
    let uid = process.pid
    // 
    let dstat = spawn('dstat',[])
    process.stdout.write("start dstat process")

    dstat.stdout.on("data", (data)=>{
        process.stdout.write(data)
    })

    Array.from(["uncaughtException","SIGTERM"]).forEach(sig =>{
        process.on(sig, (code)=>{
            console.error('>>> ',uid,'disconnected');
            // 断开
            dstat.kill()
            process.exit()
        });
    })

}else{
    let body = fs.readFileSync('./_dstat.html')
    process.stdout.write('HTTP/1.0 200 OK\r\n')
    process.stdout.write('Content-Type: text/html; charset=utf-8\r\n')
    process.stdout.write('Connection: close\r\n')
    process.stdout.write('Content-Lenght: ' + body.length + '\r\n\r\n')
    process.stdout.write(body)
}
