#!/usr/bin/ruby
require "pathname"

req_path = ENV["req_param_name"]
req_path = "../www/#{req_path}"
req_path = req_path.gsub("../","")
_file = `file -i #{req_path}`.chomp.split(":")
file_name = _file[0]
file_mime = _file[1]

if file_mime.nil? or file_mime.include? "cannot open"
  print "HTTP/1.1 404 Not Found\r\n\r\n"
  return
end

ext = file_name.scan(/\.(.+?)$/).pop
if not ext.nil?
  file_mime = case ext.pop
              when "html"
                "text/html"
              when "css"
                "text/css"
              when "js"
                "application/javascript"
              when "json"
                "application/json"
              when "txt"
                "text/plain"
              when "jpeg","jpg"
                "image/jpeg"
              when  "png"
                "image/png"
              else
                file_mime
              end + "; charset=utf-8"
end

if ENV["req_param_opt"] == "download"
  _body = "#{`cat #{file_name}`}"
  print "HTTP/1.1 200 OK\r\n"
  print "Content-Type: application/download\r\n"
  print "Content-Disposition: attachment; filename=#{file_name}\r\n\r\n"
  print "Content-Length: #{_body.length}\r\n\r\n"
  print _body
  return
end


print "HTTP/1.1 200 OK\r\n"
print "Content-Length: #{`wc -c #{file_name}`.to_i}\r\n"
print "Content-Type: #{file_mime}\r\n"
print "Connection: close\r\n\r\n"
print `cat #{file_name}`
