#!/usr/bin/env ruby

require 'json'
require_relative '../_base_'

Q.map(:GET) do |v|
  Q.ok_html `XDG_RUNTIME_DIR=/run/user/1000 WAYLAND_DISPLAY=wayland-0 notify-send -a "From " -t 30000 -A OK "#{v}"`
end
 
Q.map(:POST) do |_|
  Q.recv {|chunk|
    Q.ok_html `XDG_RUNTIME_DIR=/run/user/1000 WAYLAND_DISPLAY=wayland-0 notify-send -a "From " -t 30000 -A OK "#{chunk}"`
  }
end
