#!/usr/bin/env ruby

require 'json'
require_relative '../_base'

Q.on(:GET) do |r|
    if Q.param('argv_1') == 'upload' and Q.param('argv_2') == 'del'
         r.ok_html `rm -rv /tmp/upload`
    end
    resp 301, 'Moved Permanently', '', '', {'Location' => "#{`/home/hawk/Sync/bin/getcpolaraddr | grep https`}"}
end