#!/usr/bin/env ruby

require "sqlite3"
require_relative '../_init_'

$dist = "#{ENV['HOME']}/Documents/website/dist"
system("mkdir -qp #{$dist}")
$db = SQLite3::Database.new "#{ENV['HOME']}/Documents/website/website.db"
$db.results_as_hash = true

Q.map(:GET, '/list') do |req, resp|
  whereSql = "id IN (SELECT MAX(id) FROM posts WHERE rid != 0 GROUP BY rid UNION SELECT id FROM posts WHERE rid = 0 AND id NOT IN (SELECT rid FROM posts WHERE rid != 0))"
  rst = $db.execute("SELECT * FROM posts WHERE #{whereSql} ORDER BY id LIMIT ?, 10", [req.param_count.to_i]).map do |art|
    art
  end
  resp.ok_json(rst).finally
end

Q.map(:GET, %r{/article/(?<id>.*)}) do |req, resp|
  rst = $db.execute("SELECT * FROM posts WHERE id = ?",[req.match[:id]]).first
  resp.html('./article_md.html').render do |art|
    art.merge! rst
  end.finally
end

Q.map :GET do |_, resp|
  resp.html.render do |v|
    v.HOT = [1,2,3]
    v.WZFL = ['Linux', 'Bash', 'Docker', 'Nginx']
    v.RMBQ = ['Linux','Dokcer','Rust','Ruby']
  end.finally
end


Q.map do |_, r|
  r.fail_404 ENV.to_a.to_json
end
