#!/usr/bin/ruby
require_relative '../_init_'
require 'mime/types'

Q.map(:GET, %r|^/static/.*| ) do |q, r|
    Q.ok_json ENV.to_a.to_json
    file = Pathname.new "./static/#{q.argv_1}"
    Q.ok "#{MIME::Types.of(file.to_s).first.to_s}; charset=utf-8", file.read if file.exist? and file.file?
    Q.resp_404 "Script Not found File #{file}"
end
