#!/usr/bin/ruby

require_relative '../_init_'
require 'mime/types'

Q.map(:GET, %r|^/static/name/(.*)| ) do |r, resp|
    file = Pathname.new "./static/#{r.match_1}"
    resp.ok(file.read).type("#{MIME::Types.of(file.to_s).first.to_s}; charset=utf-8").finally if file.exist? and file.file?
    Q.resp_404 "Script Not found File #{file}"
end
