#!/usr/bin/node

let fs = require('fs')
const Q = require('../_base')


Q.on(Q.Method.GET, (r)=>{
  let type = Q.param('argv_1')
  if(type){
    if(type == 'text'){
      let file_path = `/tmp/upload/${Q.param('argv_2')}`
      if(fs.existsSync(file_path)){
        let file = fs.readFileSync(file_path,'utf-8');
        Q.ok('text/text; charset=utf-8',JSON.parse(file).content)
      }else{
        Q.resp_404('文件不存在')
      }
    }
  }
  Q.resp_500('参数错误， 或文件不存在')
});


Q.on(Q.Method.WEBSOCKET, (r) => {
  Q.recv((data) => {
    if (data) {
      console.error(`>>> [${uid}] req_body`, data.toString())
    }
  })
})
