#!/usr/bin/ruby
mark = %Q|<html>

<head>
  <title>hawk rust page</title>
</head>

<body>
  <div id="time"></div>
  <canvas id="canvas"> </canvas>
  <script>
    let tm = document.getElementById("time")
    setInterval(function () {
      tm.innerHTML = Date()
    }, 1000)
    let cs = document.getElementById("canvas")
    let ctx = cs.getContext('2d')
    ctx.arc(95, 50, 40, 0, 2 * Math.PI);
    ctx.stroke(); 
    
    ctx.moveTo(0, 0);
    ctx.lineTo(200, 100);
    ctx.stroke(); 


  </script>
</body>

</html>|

if ENV["req_body_method"] == "WEBSOCKET"
loop do
m = STDIN.readline
puts "recv: #{m}"
end
else
puts "HTTP/1.1 200 OK\r\n"
puts "Content-Type: text/html;charset=utf-8\r\n"
puts "\r\n"
puts mark
end