#!/usr/bin/env ruby


require_relative '../_init_'

Q.map(:GET, ->(v){ v == '/'}) do |req, r|
  abc = 123
  @title="The Test Page"
  r.body(File.read("page.html")).html.render do |c|
    #@title= "12344"
    c.title = "The test"
  end
end

Q.map :POST do |_, r|
    Q.on_data do |body|
        Q.log ">>> #{body}"
        Q.ok_html('done')
    end
end

Q.map :WEBSOCKET do
    Q.on_data do |chunk|
        Q.log ">>>>>>>>>>>> socket recv #{chunk}"
        Q.write '', true
    end
end
