#!/usr/bin/env ruby


require_relative '../_init_'

Q.map(:GET, ->(v){ v == '/'}) do |req, r|
  @title="The Test Page"
  r.body(File.read("page.html")).html.render do |c|
    c.title = "The test"
  end
end

Q.map :POST do |_, r|
    Q.recv do |v|
        r.body  v
    end
end

Q.map :WEBSOCKET do
    Q.on_data do |chunk|
        Q.log ">>>>>>>>>>>> socket recv #{chunk}"
        Q.write '', true
    end
end
