#!/usr/bin/env ruby


require_relative '../_base_'
Q.log `pwd`

Q.map(:GET, lambda {|v| v == '/test/test'}) do |v1,v2|
    Q.log "recv args #{v1},#{v2}"
    Q.ok_html 'ok la'
end

Q.map(:POST,'/test/test') do |v1|
    Q.recv do |body|
        Q.log ">>> #{body}"
        Q.ok_html('done')
    end
end

Q.map :WEBSOCKET, '/test/test' do |v1|
    Q.on_data do |chunk|
        Q.log ">>>>>>>>>>>> socket recv #{chunk}"
        Q.write '', true
    end
end