#!/usr/bin/env ruby


require_relative '../_init_'

Q.map(:GET, ->(v){ v == '/'}) do |_, r|
  r.body(File.read("page.html")).html.render do |ctx|
    ctx.title = "test"
  end
end

Q.map :POST do |_, r|
    Q.on_data do |body|
        Q.log ">>> #{body}"
        Q.ok_html('done')
    end
end

Q.map :WEBSOCKET do
    Q.on_data do |chunk|
        Q.log ">>>>>>>>>>>> socket recv #{chunk}"
        Q.write '', true
    end
end
