#!/usr/bin/env ruby

require_relative '../_init_'
html_page = './page.html'

Q.map :GET do |_, resp|
  aaa = 123
  if File.readable?(html_page)
    @bbb = 789
    resp.page(html_page).html.render do |v|
      v.title = 'Test Page'
    end.finally
  else
    resp.fail_404 ENV.to_a.to_json
  end
end

require 'json'
Q.map :WEBSOCKET do |_|
  Q.notify(4444) do |val, id|
    Q.log("============消息#{id} SELF #{Process.pid}==========")
    Q.write val
  end

  Q.recv do |val|
    Q.notify val
    Q.write val
  end
end

Q.map do |_, r|
  r.fail_404 ENV.to_a.to_json
end
